# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_MARVELL_10G_PHY)	+= marvell10g.o
marvell-y			:= marvell_main.o
obj-$(CONFIG_MARVELL_PHY)	+= marvell.o
obj-$(CONFIG_MARVELL_88Q2XXX_PHY)	+= marvell-88q2xxx.o
obj-$(CONFIG_MARVELL_88X2222_PHY)	+= marvell-88x2222.o
